### ISSUE TITLE
The latest version of the compiler between Swift2.5 and Swift3 compilation problems

### ISSUE THREAD

**Issue by guodongZhao** [liuyujiahuan/FamilyMedicine#1]
The latest version of the compiler between Swift2.5 and Swift3 compilation problems
The following：⤵️😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂
The workspace has projects that contain source code developed with an earlier version of Swift.

Choose “Convert” to update the source code in these projects to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.

This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

**Comment by liuyujiahuan** [comment]
这个是之前备课时写的，用swift2.2写的，如果你是Xcode8的话，就转成Swift2.3吧。等我更新到3.0。应该没时候了，没时间
